openapi: "3.0.0"
info:
  title: Influx OSS API Service
  version: 2.0.0
servers:
  - url: /
paths:
#REF_COMMON_PATHS
  health:
    $ref: "./oss/paths/health.yml"
  ready:
    $ref: "./oss/paths/ready.yml"
  api/v2/users:
    $ref: "./common/paths/users.yml"
  api/v2/users/{userID}:
    $ref: "./common/paths/users_userID.yml"
  api/v2/setup:
    $ref: "./common/paths/setup.yml"
  api/v2/authorizations:
    $ref: "./common/paths/authorizations.yml"
  api/v2/authorizations/{authID}:
    $ref: "./common/paths/authorizations_authID.yml"
  api/v2/variables:
    $ref: "./common/paths/variables.yml"
  api/v2/variables/{variableID}:
    $ref: "./common/paths/variables_variableID.yml"
components:
  parameters:
#REF_COMMON_PARAMETERS
  schemas:
#REF_COMMON_SCHEMAS
    Authorization:
      $ref: "./common/schemas/Authorization.yml"
    AuthorizationPostRequest:
      $ref: "./common/schemas/AuthorizationPostRequest.yml"
    Authorizations:
      $ref: "./common/schemas/Authorizations.yml"
    Permission:
      $ref: "./common/schemas/Permission.yml"
    Resource:
      $ref: "./common/schemas/Resource.yml"
    User:
      $ref: "./common/schemas/User.yml"
    Users:
      $ref: "./common/schemas/Users.yml"
    OnboardingRequest:
      $ref: "./common/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./common/schemas/OnboardingResponse.yml"
    Variable:
      $ref: "./common/schemas/Variable.yml"
    Variables:
      $ref: "./common/schemas/Variables.yml"
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
